### PR TITLE
fix(templates): Tap template: fix style and docstrings, and add test cases for SQL and "Other" sources

### PR DESCRIPTION
**Pull request by flexponsive**
Follow-up to #1410: Now all tap templates are covered by e2e tests

- Add replay file for tap from SQL source and Other source
- Fix mypy + docstring errors

----
:books: Documentation preview :books:: https://meltano-sdk--1434.org.readthedocs.build/en/1434/

### CODE REVIEW

**Comment by tayloramurphy** [comment]
Thanks for the PR @flexponsive - looks like we've got some engineers on it as reviewers 👍

**Review by edgarrmondragon — COMMENTED** [review]
@flexponsive should we add these new cases to the GitHub workflow file?

**Comment by flexponsive** [comment]
@edgarrmondragon good catch! thanks for pointing it out. added the missing cases

**Review by edgarrmondragon — APPROVED** [review]

**Comment by edgarrmondragon** [comment]
thanks @flexponsive!

**Pull request merged**
