### PR TITLE
feat: move to furo theme

### PR DESCRIPTION
**Pull request by kgpayne**
Builds on the work @edgarrmondragon has already done to reorganise the docs 🙌

----
:books: Documentation preview :books:: https://meltano-sdk--1381.org.readthedocs.build/en/1381/

### CODE REVIEW

**Review by WillDaSilva — COMMENTED** [review]
Overall, this is beautiful. Thank you for doing this!

On small issue: the search bar touches the main content area on the right.

**Comment by aaronsteers** [comment]
@kgpayne and @edgarrmondragon - Any preference on merging this into #1353 and then reviewing #1353 for final changes and organization?

Versus reviewing all changes here as the "final" review of what to be merged into `main`?

**Comment by kgpayne** [comment]
@WillDaSilva that's a feature 😅 https://furo.readthedocs.io

We may like to fiddle with the search bars background color and border to replicate the Divio example @cjohnhanson [shared](https://documentation.divio.com).

**Comment by aaronsteers** [comment]
Just focusing on nav structure, for which we want to reduce later breaking changes:

1. I think the three-level makes this a bit tricky to find. Since we already have another "Guide" at top level, how about moving these up a level to be either `.../migration/<pagename>` ("Migration Guides" as the parent title) or `../guides/<pagename>` ("In Depth Guides" as the parent title):
  - > image

All the other nesting looks great! I see `.../advanced/...`, `.../implementation/...`, `.../classes/...` - all those make sense and seem stable to me.

**Comment by edgarrmondragon** [comment]
> Any preference on merging this into #1353 and then reviewing #1353 for final changes and organization?

@aaronsteers I see you already made some valuable suggestions, so I'd say we merge, quote your suggestions in #1353 and continue reviewing there if you're ok with that

**Review by aaronsteers — APPROVED** [review]
Per @edgarrmondragon's feedback in thread, approving for merge into the other PR - and we'd do final review there on https://github.com/meltano/sdk/pull/1353

**Review by edgarrmondragon — APPROVED** [review]

**Comment by aaronsteers** [comment]
Some other small reorg notes, none of which are breaking so if we want to hold for now, we totally can:

- These could be moved under the `Reference` section header (but not under `../classes/..` directory, since that's something different):
  - [JSON Schema Builder](https://meltano-sdk--1381.org.readthedocs.build/en/1381/typing.html)
  - [Plugin Capabilities](https://meltano-sdk--1381.org.readthedocs.build/en/1381/capabilities.html)
  - [Command Line Samples](https://meltano-sdk--1381.org.readthedocs.build/en/1381/cli_commands.html) - which we could rename to `Command Line Reference` without changing the URL (`./cli_comands.html`)

**Comment by aaronsteers** [comment]
Merged. 🚀 

Follow-ups will carry over to

- https://github.com/meltano/sdk/pull/1353

**Pull request merged**
