### PR TITLE
docs: Generate documentation for constructor parameters

### PR DESCRIPTION
**Pull request by edgarrmondragon**
- Document method parameters.
- Add `nox` task for live-reloading docs.

Current state: https://sdk.meltano.com/en/latest/classes/singer_sdk.Stream.html#singer_sdk.Stream

vs

Preview: https://meltano-sdk--900.org.readthedocs.build/en/900/classes/singer_sdk.Stream.html#singer_sdk.Stream

### CODE REVIEW

**Review by WillDaSilva — APPROVED** [review]
Is it possible to render both the signatures and the detailed parameter / return value content? If so I think that would be ideal. In either case, this looks good to me.

**Comment by edgarrmondragon** [comment]
> Is it possible to render both the signatures and the detailed parameter / return value content? If so I think that would be ideal. In either case, this looks good to me.

@WillDaSilva good idea! I think I've solved that now by explicitly requesting `__init__` gets the same treatment as other methods using `:special-members: __init__`.

**Comment by WillDaSilva** [comment]
@edgarrmondragon Could you please provide an updated preview link? I'm not sure how you generated it - I don't see any CI actions for it.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon Could you please provide an updated preview link? I'm not sure how you generated it - I don't see any CI actions for it.

@WillDaSilva It's up-to-date with the changes in this PR. Builds are triggered in [readthedocs](https://readthedocs.org/projects/meltano-sdk/builds/) but it's failing to report back to GitHub in the PR checks.

**Review by WillDaSilva — APPROVED** [review]

**Pull request merged**
