### PR TITLE
feat: Add stream context to request authenticator

### PR DESCRIPTION
**Pull request by mchudoba**
Closes https://github.com/meltano/sdk/issues/1028

----
:books: Documentation preview :books:: https://meltano-sdk--1029.org.readthedocs.build/en/1029/

### CODE REVIEW

**Comment by mchudoba** [comment]
If this is accepted, and depending on whether or not we want to deprecate the `authenticator` property, I can go through and update the cookiecutter templates and code samples with this new method.

**Comment by tayloramurphy** [comment]
@mchudoba is there still interest on your end to get this merged? cc @edgarrmondragon

**Comment by mchudoba** [comment]
> @mchudoba is there still interest on your end to get this merged? cc @edgarrmondragon

@tayloramurphy We ended up finding a way to work around this, so I don't explicitly need it anymore. I'd be happy to get this updated for merging if you have an interest in it, otherwise feel free to close.

**Comment by tayloramurphy** [comment]
@mchudoba currently @edgarrmondragon is on PTO but I would defer to him on this. He'll be back in a week or so and will likely chime in then.

**Comment by edgarrmondragon** [comment]
I'm closing this since there are simple workarounds

**Pull request closed without merging**
