### PR TITLE
feat: Support `requests.auth` authenticators

### LINKED ISSUE #1105: [Feature]: Allow built-in request authentication helpers to be used
### Feature scope

Taps (catalog, state, stream maps, etc.)

### Description

Some of these are nice, and would at least remove from duplication on our side:

- [requests.auth.HTTPBasicAuth(username, password)](https://requests.readthedocs.io/en/latest/_modules/requests/auth/#HTTPBasicAuth)
Attaches HTTP Basic Authentication to the given Request object.

- [requests.auth.HTTPProxyAuth(username, password)](https://requests.readthedocs.io/en/latest/_modules/requests/auth/#HTTPProxyAuth)
Attaches HTTP Proxy Authentication to a given Request object.

- [requests.auth.HTTPDigestAuth(username, password)](https://requests.readthedocs.io/en/latest/_modules/requests/auth/#HTTPDigestAuth)
Attaches HTTP Digest Authentication to the given Request object.

https://requests.readthedocs.io/en/latest/api/#authentication

Custom authenticators are also interesting, and developers would be able to leverage existing auth packages in the wild:

- https://github.com/tedder/requests-aws4auth
- https://github.com/pyauth/requests-http-signature
- https://github.com/Colin-b/requests_auth

https://requests.readthedocs.io/en/latest/user/advanced/#custom-authentication

---

The implementation seems easy enough as we already did most of the work in https://github.com/meltano/sdk/pull/842. We'd only need to add a `__call__` method to the base auth class:

```python
class APIAuthenticatorBase:
    def __call__(self, request):
        return self.authenticate_request(request)
```

and also set the `auth` attribute of the session:

```python
class RESTStream:
    def build_prepared_request(
        self,
        *args: Any,
        **kwargs: Any,
    ) -> requests.PreparedRequest:
        ...
        self.requests_session.auth = self.authenticator
        return self.requests_session.prepare_request(request)
```

### PR DESCRIPTION
**Pull request by edgarrmondragon**
Closes #1105 

----
:books: Documentation preview :books:: https://meltano-sdk--1109.org.readthedocs.build/en/1109/

### CODE REVIEW

**Review by cjohnhanson — APPROVED** [review]

**Review by afolson — APPROVED** [review]

**Comment by aaronsteers** [comment]
@edgarrmondragon - This one went under my radar and I'm just reading through now. Can you add a usage example in one of the samples, or in the `Code Samples` section, or similar? I'm not super familiar with this and I think a sample usage would be helpful also for devs who want to leverage this.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon - This one went under my radar and I'm just reading through now. Can you add a usage example in one of the sample implementations, or in the `Code Samples` section, or similar? I'm not super familiar with this and I think a sample usage would be helpful also for devs who want to leverage this.
> 
> Or is it proper to think of this as fully internal to the SDK and the dev-side experience is basically the same?

@aaronsteers thanks for taking a look! I've added a simple example with links to community-supported authentication classes:

https://meltano-sdk--1109.org.readthedocs.build/en/1109/code_samples.html#use-one-of-requests-s-built-in-authenticators

**Comment by aaronsteers** [comment]
@edgarrmondragon - Super helpful!! Thank you!

I was going to ask for links and then realized they are already linked 😅.

LGTM!

**Review by aaronsteers — APPROVED** [review]
Feel free to merge when ready. 🚀

**Pull request merged**
