### PR TITLE
refactor(taps): Change `SQLStream.schema` into a cached property

### PR DESCRIPTION
**Pull request by mjsqu**
Schema is called at least once per record and does not change within a stream, so it should be cached for performance benefits.

https://app.slack.com/client/TFG99TU9K/C013Z450LCD/thread/C013Z450LCD-1685703921.187269

----
:books: Documentation preview :books:: https://meltano-sdk--1745.org.readthedocs.build/en/1745/

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
@mjsqu can you fix the failing mypy check? Some of the conversation in https://github.com/python/mypy/issues/5107#issuecomment-529372406 might be helpful.

Thanks!

**Comment by mjsqu** [comment]
I had a quick attempt at this, but it didn't work particularly well - plus I think the proposed solution in the thread sets the lru_cache decorator to do nothing (`pass`), which removes the benefit?

I think I need to follow the example by @qbatten:
https://github.com/meltano/sdk/pull/1394/commits/0b5d6b0e4b07c93290f68b62e1f807f9e7217ccd

**Comment by mjsqu** [comment]
@edgarrmondragon 🥳 

Thanks for the inspiration @qbatten

**Review by edgarrmondragon — APPROVED** [review]
Thanks @mjsqu!

**Pull request merged**
